class Parameters:
    def __init__(self, string: str) -> None: ...
    def __str__(self) -> str: ...

class Pairing:
    def __init__(self, params: Parameters) -> None: ...
    def order(self) -> int: ...
    def apply(self, e1: "Element", e2: "Element") -> "Element": ...
    def is_symmetric(self) -> bool: ...

class Element:
    def __init__(self, pairing: Pairing, type: int, string: str) -> None: ...
    @staticmethod
    def from_int(pairing: Pairing, value: int) -> "Element": ...
    @staticmethod
    def random(pairing: Pairing, type: int) -> "Element": ...
    @staticmethod
    def zero(pairing: Pairing, type: int) -> "Element": ...
    @staticmethod
    def one(pairing: Pairing, type: int) -> "Element": ...
    @staticmethod
    def from_hash(pairing: Pairing, type: int, data: bytes) -> "Element": ...
    def to_bytes(self) -> bytes: ...
    def to_bytes_compressed(self) -> bytes: ...
    def to_bytes_x_only(self) -> bytes: ...
    @staticmethod
    def from_bytes(pairing: Pairing, type: int, data: bytes) -> "Element": ...
    @staticmethod
    def from_bytes_compressed(pairing: Pairing, type: int, data: bytes) -> "Element": ...
    @staticmethod
    def from_bytes_x_only(pairing: Pairing, type: int, data: bytes) -> "Element": ...
    def order(self): ...
    def __getitem__(self, index: int) -> "Element": ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...
    def __add__(self, other: "Element") -> "Element": ...
    def __sub__(self, other: "Element") -> "Element": ...
    def __mul__(self, other: "Element | int") -> "Element": ...
    def __truediv__(self, other: "Element") -> "Element": ...
    def __pow__(self, other: "Element | int") -> "Element": ...
    def __neg__(self) -> "Element": ...
    def __invert__(self) -> "Element": ...
    def __eq__(self, other: "Element") -> bool: ...
    def __ne__(self, other: "Element") -> bool: ...
    def is0(self) -> bool: ...
    def is1(self) -> bool: ...

G1: int
G2: int
GT: int
ZR: int
